/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Dominic Baker (https://sketchfab.com/Domuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nft-art-by-domuk-abstract-art-e49701ad2fde4d0e9ee8604adb4e36ae
Title: NFT Art by Domuk abstract art
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const NFT=(props)=> {
    const { animation, ...rest } = props;
    const group = useRef();
    const { nodes, materials, animations } = useGLTF('/nft_art_by_domuk_abstract_art.glb');
    // const { actions, names } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Text_0"
                position={[-0.029, 0.043, -0.251]}
                rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group name="Cube_1" position={[1.554, 0.275, -0.298]} scale={[1.917, 1, 0.246]}>
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.Material}
                />
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials['Material.001']}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default NFT;
