version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genx-ai
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
    environment:
      - ENVIRONMENT=development
      - DEBUG=1
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge